# Generated by Django 5.0.2 on 2024-02-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='last_login',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
