# Generated by Django 5.0.2 on 2024-02-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0004_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_data',
            field=models.CharField(max_length=100000),
        ),
    ]
