# Generated by Django 5.0.2 on 2024-02-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0010_alter_images_image_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.IntegerField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(default='null', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='image_data',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
