# Generated by Django 5.0.2 on 2024-02-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0011_users_age_users_gender_users_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='age',
        ),
        migrations.RemoveField(
            model_name='users',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone',
        ),
    ]
