# Generated by Django 5.0.2 on 2024-02-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0012_remove_users_age_remove_users_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(default='null', max_length=15),
            preserve_default=False,
        ),
    ]
