# Generated by Django 5.0.2 on 2024-03-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0015_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500)),
                ('emotion', models.CharField(max_length=50)),
                ('userId', models.CharField(max_length=50)),
                ('detected_at', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
