# Generated by Django 5.0.2 on 2024-03-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0017_alter_emotionhistory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionhistory',
            name='detected_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
